

#ifndef _ELF_ETCA_H
#define _ELF_ETCA_H

#include "elf/reloc-macros.h"

/* Relocation types.  Note: These relocation numbers are part of the ELF files, so changing them is a breaking change */
START_RELOC_NUMBERS (elf_etca_reloc_type)
  RELOC_NUMBER (R_ETCA_NONE, 0)
  RELOC_NUMBER (R_ETCA_BASE_JMP, 1) /* TODO: expand this to the EXOP JUMP opcodes */
  RELOC_NUMBER (R_ETCA_SAF_CALL, 2) /* SAF absolute call */
  RELOC_NUMBER (R_ETCA_ABM_RIS_5, 3)
  RELOC_NUMBER (R_ETCA_ABM_RIZ_5, 4)
  RELOC_NUMBER (R_ETCA_ABM_RIS_8, 5)
  RELOC_NUMBER (R_ETCA_ABM_RIZ_8, 6)
  RELOC_NUMBER (R_ETCA_ABM_RIS_16, 7)
  RELOC_NUMBER (R_ETCA_ABM_RIZ_16, 8)
  RELOC_NUMBER (R_ETCA_ABM_RIS_32, 9)
  RELOC_NUMBER (R_ETCA_ABM_RIZ_32, 10)
  RELOC_NUMBER (R_ETCA_ABM_RIS_64, 11)
  RELOC_NUMBER (R_ETCA_ABM_RIZ_64, 12)
  RELOC_NUMBER (R_ETCA_MOV_5,  13)
  RELOC_NUMBER (R_ETCA_MOV_10, 14)
  RELOC_NUMBER (R_ETCA_MOV_15, 15)
  RELOC_NUMBER (R_ETCA_MOV_16, 16)
  RELOC_NUMBER (R_ETCA_MOV_20, 17)
  RELOC_NUMBER (R_ETCA_MOV_25, 18)
  RELOC_NUMBER (R_ETCA_MOV_30, 19)
  RELOC_NUMBER (R_ETCA_MOV_32, 20)
  RELOC_NUMBER (R_ETCA_MOV_35, 21)
  RELOC_NUMBER (R_ETCA_MOV_40, 22)
  RELOC_NUMBER (R_ETCA_MOV_45, 23)
  RELOC_NUMBER (R_ETCA_MOV_50, 24)
  RELOC_NUMBER (R_ETCA_MOV_55, 25)
  RELOC_NUMBER (R_ETCA_MOV_60, 26)
  RELOC_NUMBER (R_ETCA_MOV_64, 27)
END_RELOC_NUMBERS (R_ETCA_max)

#define SHT_ETCA_ATTRIBUTES 0x70000003

/* Object attributes.  */
enum
{
    /* 0-3 are generic.  */
    Tag_ETCA_cpuid = 4,
};

#endif